import SwiftUI

struct ChatView: View {
    @State private var messages: [ChatMessage] = []
    @State private var inputText = ""
    @State private var suggestedQuestions = SuggestedQuestion.defaultQuestions

    var body: some View {
        VStack(spacing: 0) {
            // Custom left-aligned header
            HStack {
                Text("Chat")
                    .font(.system(size: 28, weight: .bold))
                    .foregroundStyle(.black)
                Spacer()
            }
            .padding(.horizontal, 20)
            .padding(.top, 16)
            .padding(.bottom, 8)
            .background(Color(red: 0.95, green: 0.95, blue: 0.95))
            .frame(maxWidth: .infinity)
            .zIndex(1)

            ZStack {
                Color(red: 0.95, green: 0.95, blue: 0.95)

                VStack(spacing: 0) {
                    ScrollView {
                        VStack(spacing: 16) {
                            // Initial state with suggestions
                            if messages.isEmpty {
                                // Audio icon
                                Circle()
                                    .fill(Color.white.opacity(0.8))
                                    .frame(width: 80, height: 80)
                                    .overlay(
                                        Image(systemName: "waveform")
                                            .font(.system(size: 30))
                                            .foregroundStyle(.gray)
                                    )
                                    .padding(.top, 60)
                                    .padding(.bottom, 20)

                                Text("You may be interested in")
                                    .font(.system(size: 16))
                                    .foregroundStyle(.gray)
                                    .padding(.bottom, 10)

                                ForEach(suggestedQuestions) { question in
                                    SuggestedQuestionCard(question: question.text) {
                                        sendMessage(question.text)
                                    }
                                }

                                Spacer(minLength: 100)
                            } else {
                                // Chat messages
                                ForEach(messages) { message in
                                    MessageBubble(message: message)
                                }
                                .padding(.top, 20)
                            }
                        }
                        .padding(.horizontal, 20)
                    }
                    .scrollIndicators(.hidden)

                    // Input area
                    VStack(spacing: 8) {
                        // Disclaimer
                        Text("Answers are generated by a neural network: we are not responsible for the accuracy of the information.")
                            .font(.system(size: 11))
                            .foregroundStyle(.gray)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 20)

                        // Input field
                        HStack(spacing: 12) {
                            Image(systemName: "sparkles")
                                .foregroundStyle(.gray)
                                .font(.system(size: 20))

                            TextField("Ask a question...", text: $inputText)
                                .font(.system(size: 16))

                            Button(action: {
                                if !inputText.isEmpty {
                                    sendMessage(inputText)
                                    inputText = ""
                                }
                            }) {
                                Image(systemName: "paperplane.fill")
                                    .foregroundStyle(.white)
                                    .font(.system(size: 18))
                                    .frame(width: 40, height: 40)
                                    .background(
                                        Circle()
                                            .fill(Color.gray.opacity(0.8))
                                    )
                            }
                        }
                        .padding(.horizontal, 20)
                        .padding(.vertical, 12)
                        .background(
                            RoundedRectangle(cornerRadius: 25)
                                .fill(Color(red: 0.2, green: 0.2, blue: 0.2))
                        )
                        .padding(.horizontal, 20)
                        .padding(.bottom, 10)
                    }
                    .background(Color(red: 0.95, green: 0.95, blue: 0.95))
                }
            }
        }
    }

    private func sendMessage(_ text: String) {
        messages.append(ChatMessage(text: text, isUser: true))
        Task {
            try? await Task.sleep(for: .seconds(1))
            messages.append(ChatMessage(
                text: "This is a placeholder response. In a real app, this would connect to an AI service to provide meaningful answers about manifestation and abundance.",
                isUser: false
            ))
        }
    }
}

struct SuggestedQuestionCard: View {
    let question: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(question)
                .font(.system(size: 15))
                .foregroundStyle(.black)
                .multilineTextAlignment(.leading)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(20)
                .background(
                    RoundedRectangle(cornerRadius: 16)
                        .fill(Color.white)
                )
        }
    }
}

struct MessageBubble: View {
    let message: ChatMessage

    var body: some View {
        HStack {
            if message.isUser {
                Spacer()
                Text(message.text)
                    .font(.system(size: 15))
                    .foregroundStyle(.white)
                    .padding(16)
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(Color.blue)
                    )
                    .frame(maxWidth: 280, alignment: .trailing)
            } else {
                Text(message.text)
                    .font(.system(size: 15))
                    .foregroundStyle(.black)
                    .padding(16)
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(Color.white)
                    )
                    .frame(maxWidth: 280, alignment: .leading)
                Spacer()
            }
        }
    }
}
